/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.interf;

import edu.esprit.dao.DepotDAO;
import edu.esprit.dao.StockDAO;
import edu.esprit.entities.Depot;
import edu.esprit.entities.Stock;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author OUESLATI
 */
public class AddStock extends javax.swing.JFrame {

    /**
     * Creates new form AddStock
     */
    public AddStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        LabelAjouterStock = new javax.swing.JLabel();
        LabelType = new javax.swing.JLabel();
        RadioFemme = new javax.swing.JRadioButton();
        RadioHomme = new javax.swing.JRadioButton();
        LabelQuant = new javax.swing.JLabel();
        SpinnerQuant = new javax.swing.JSpinner();
        LabelDepot = new javax.swing.JLabel();
        ComboBoxDepot = new javax.swing.JComboBox();
        ButtonAjouter = new javax.swing.JButton();
        ButtonQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LabelAjouterStock.setText("Ajouter un Stock");

        LabelType.setText("Type Vetements");

        buttonGroup1.add(RadioFemme);
        RadioFemme.setText("Femme");

        buttonGroup1.add(RadioHomme);
        RadioHomme.setText("Homme");
        RadioHomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioHommeActionPerformed(evt);
            }
        });

        LabelQuant.setText("Quantite");

        LabelDepot.setText("Depot");

        ComboBoxDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDepotActionPerformed(evt);
            }
        });

        ButtonAjouter.setText("Ajouter");
        ButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjouterActionPerformed(evt);
            }
        });

        ButtonQuitter.setText("Quitter");
        ButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelQuant)
                            .addComponent(LabelDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxDepot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpinnerQuant, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelType)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAjouterStock)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioFemme)
                                .addGap(38, 38, 38)
                                .addComponent(RadioHomme)))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(ButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelAjouterStock)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelType)
                    .addComponent(RadioFemme)
                    .addComponent(RadioHomme))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelQuant)
                    .addComponent(SpinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDepot)
                    .addComponent(ComboBoxDepot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAjouter)
                    .addComponent(ButtonQuitter))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioHommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioHommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioHommeActionPerformed

    private void ComboBoxDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDepotActionPerformed
        
    }//GEN-LAST:event_ComboBoxDepotActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        DepotDAO depotDAO = new DepotDAO();
        List<Depot> depots = depotDAO.DisplayAllDepots();
        for(Depot d : depots)
          {
            ComboBoxDepot.addItem(d.getAdresse_depot());
          }
    
    }//GEN-LAST:event_formWindowOpened

    private void ButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQuitterActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonQuitterActionPerformed

    private void ButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjouterActionPerformed
        // TODO add your handling code here:
        String type = "";
        if(RadioFemme.isSelected())
        {
            type = RadioFemme.getText();
        }
        if(RadioHomme.isSelected())
        {
            type = RadioHomme.getText();
        }
        String qt_string = SpinnerQuant.getValue().toString();
        int qt = Integer.parseInt(qt_string);
        
        DepotDAO depotDAO = new DepotDAO();
        Depot d = depotDAO.findDepotByAdresse(ComboBoxDepot.getSelectedItem().toString());
        Stock stock = new Stock();
        stock.setDepot(d);
        stock.setNombre_articles(qt);
        stock.setType_vet_stock(type);
        StockDAO stockDAO = new StockDAO();
        stockDAO.insertStock(stock);
        JOptionPane.showMessageDialog(this, "Jawek 7aféli!!");
    }//GEN-LAST:event_ButtonAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStock().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAjouter;
    private javax.swing.JButton ButtonQuitter;
    private javax.swing.JComboBox ComboBoxDepot;
    private javax.swing.JLabel LabelAjouterStock;
    private javax.swing.JLabel LabelDepot;
    private javax.swing.JLabel LabelQuant;
    private javax.swing.JLabel LabelType;
    private javax.swing.JRadioButton RadioFemme;
    private javax.swing.JRadioButton RadioHomme;
    private javax.swing.JSpinner SpinnerQuant;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    // End of variables declaration//GEN-END:variables
}
